routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/posts', 'PostsController');

app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    protected $fillable = ['title','content','user_id'];

    public function user() {
        return $this->belongsTo(User::class);
    }
    /**
     * Faire des requête complexe dans une methode
     *
     * @param [type] $query
     * @param [type] $user
     * @return void
     */
    public function scopeUserPost($query,$user)
    {
        return $query->where('user_id',$user);
    }
    /**
     * Getter & Setter Mutateur
     * getNomduchampAttribute()
     * @param [type] $value
     * @return void
     */
    public function getTitleAttribute($value)
    {
        return strtoupper($value);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
       return $this->hasMany(User::class); 
    }

    public function isAdmin()
    {
        return $this->role === 'admin';
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Symfony\Component\Console\Input\Input;
use Illuminate\Support\Facades\Auth;
use App\Posts;
use Symfony\Component\HttpFoundation\Session\Session;
use Illuminate\Support\Facades\Gate;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index()
    {
        if(Auth::check()){
            $posts = Posts::userPost(Auth::id())->get();
            return view('posts.index', compact('posts'));
        }
        return redirect(route('login'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::check()) {
            $this->validate($request, [
                'title' => 'required',
                'content' => 'required'
            ]);
            $post = $request->all();            
            $post = array_merge($post,['user_id' => Auth::id()]);
            Posts::create($post);
            $request->session()->flash('add_post_success', 'Votre article est publié');
            return redirect(route('posts.index'));
        }
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Posts::find($id);
        $this->authorize('view',$post);
        return view('posts.single', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::check()){
            $post = Posts::findOrFail($id);
            $this->authorize('update',$post);
           
            return view('posts.edit', compact('post'));
          
                       
        } 
        return redirect()->back();    
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::check()){
            
           $post = Posts::findOrFail($id);
           $this->authorize('update',$post);
           $post->update($request->all());
           return redirect(route('welcome'));
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::check()){
            $post = Posts::findOrFail($id);
            $this->authorize('delete',$post);
            Posts::where('id',$id)->delete();
            return redirect()->back();    
        }
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Posts;

class WelcomeController extends Controller
{
    public function index()
    {
        $posts = Posts::get();
        return view('welcome', compact('posts'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Board - Cyber sécurité</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Scripts -->
   

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav>
            <div class="nav-wrapper container">
              <a href="/" class="brand-logo">Board</a>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                @guest
                    <li><a href="{{ route('login') }}">{{ __('lang.login')}}</a></li>
                    <li><a href="{{ route('register') }}">{{__('lang.register')}}</a></li>
                @else
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{ Auth::user()->name }}<i class="material-icons right">arrow_drop_down</i></a></li>
                    <ul id="dropdown1" class="dropdown-content">
                        <li>
                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                              document.getElementById('logout-form').submit();">
                                 {{ __('Logout') }}
                             </a>
                        </li>

                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                             @csrf
                         </form>
                    </ul>
                @endguest
              </ul>
            </div>
        </nav>

        <main>
            @yield('content')
        </main>
    </div>
    <script src="https://cdn.ckeditor.com/ckeditor5/11.0.1/classic/ckeditor.js"></script>
    <script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
              crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
</body>
</html>

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="text-center">Modification</h1>
        <div class="row ">
            <div class="col s12">
                <div class="card" style="padding:10px">
                    <h3>Modifier</h3>
                    @if(Session::has('add_post_success'))
                        <div class="alert alert-success">
                            {{ Session::get('add_post_success') }}
                        </div>
                    @endif
                   
                        <form method="POST" action="{{ route('posts.update',$post) }}">
                            @csrf
                            <input name="_method" type="hidden" value="PUT">
                            <div class="row">
                                <div class="input-field col s12">
                                    <label for="title">Titre</label>
                                  <input type="text" name="title" id="title" placeholder="titre" value="{{ $post->title }}">
                                      @if ($errors->has('title'))
                                          <span class="invalid-feedback" role="alert">
                                              <strong>{{ $errors->first('title') }}</strong>
                                          </span>
                                      @endif
                                  </div>

                                </div>
                                <div class="row">

                                    <div class="input-field col s12">
    
                                        <div class="form-group">
                                          <label for="editor">Contenue</label>
                                          <textarea name="content" id="editor" rows="3">{{ $post->content }}</textarea>
                                          @if ($errors->has('content'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('content') }}</strong>
                                            </span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                            <div class="row">
                                <div class="input-field col s12">
                                        <button type="submit" class="btn btn-primary">Envoyer</button>
                                </div>
                                
                            </div>
                         
                        </form>
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="text-center">Tous mes Publications</h2>
        <div class="row">
            <div class="col s12 l8">
                <div class="card" style="padding:10px">
                        @if(Session::has('add_post_success'))
                        <div class="card-panel teal lighten-2"> {{ Session::get('add_post_success') }}</div>
                        @endif
                        <form method="post" action="{{ route('posts.store')}}">
                            @csrf
                                <h4>Publier</h4>
                    
                            <div class="row">
                                <div class="input-field col s12">   
                                    <input type="text" id="email" class="validate" name="title" value="{{ old('title') }}" required/>
                                    <label for="email">Titre</label>
                                </div>
                            </div>
                            <div class="row">
                                <label for="edior">Description</label>
                                <div class="input-field col s12">   
                                    <textarea name="content" id="editor" cols="30" rows="50"></textarea>
                                    
                                </div>
                            </div>
                            <div class="row center-align">
                                    <button class="btn waves-effect waves-light" type="submit" name="action">Publier
                                        <i class="material-icons right">send</i>
                                    </button>
                            </div>
                        </form>
                     
                </div>
            </div>
        </div>

        <div class="row">
                @foreach ($posts as $post)
                    <div class="col s12 m6">
                        <div class="card blue-grey darken-1">
                          <div class="card-content white-text">
                            <span class="card-title">{{ $post->title }}</span>
                          </div>
                          <div class="card-action">
                            <a href="{{ route('posts.show', $post)}}">Voir</a>
                            @auth
                                @can('update', $post)
                                    <a href="{{ route('posts.edit', $post)}}">Editer</a>
                                @endcan
                                @can('delete', $post)
                                    <a href="{{  route('posts.destroy',$post) }}"
                                        onclick="event.preventDefault();
                                                      document.getElementById('destroy-form').submit();">
                                        Supprimer
                                    </a>
                                    <form id="destroy-form" action="{{ route('posts.destroy',$post) }}" method="post">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                    </form>
                                @endcan 
                            @endauth
                          </div>
                        </div>
                    </div>  
                @endforeach
             
            </div>
        </div>
    </div>
@endsection

resources/views/posts/single.blade.php
@extends('layouts.app')

@section('content')
    
    <div class="container">
        <h1>{{ $post->title }}</h1>
        <p>{!! $post->content !!}</p>
        <div class="col-md-8">
            @guest
            <div class="card">
                <div class="card-header">Commenter</div>

                <div class="card-body">
                <p class="text-center"><a href="{{ route('login') }}">Connecter</a> vous ou <a href="{{ route('register') }}">crée un compte</a> pour commenter </p>                        
                </div>
            </div>   
            @else
            <div class="card">
                <div class="card-header">Ajouter un commentaire</div>

                <div class="card-body">
                    <form method="post" action="{{ route('posts.store') }}">
                        @csrf
                        <div class="form-group">
                          <textarea class="form-control" name="content" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Commenter</button>
                        </div>
                    </form>
                        
                </div>
            </div>   
            @endguest
        </div>
    </div>
@endsection